apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lastmission
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:viinac/last-mission.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: lastmission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
