package com.coderhan.lastmission.shared.error;

public enum ErrorCode {
    INVALID_REQUEST,
    CHAT_ROOM_NOT_FOUND,
    CHAT_MESSAGE_INVALID,
    CHAT_MESSAGE_NOT_FOUND,
    CHAT_ACCESS_DENIED,
    CHAT_ROOM_INVALID,
    CHAT_USER_NOT_FOUND,
    CHAT_PARTICIPANT_EXISTS,
    RESERVATION_INVALID_REQUEST,
    RESERVATION_NOT_FOUND,
    RESERVATION_ACCESS_DENIED,
    RESERVATION_WAITING_ROOM_REQUIRED
}
